app:
  name: 'Mako'
  encryptionKey: 'H3@kR$8fL%gT#6Xu2sJpI7eDw9BvN0yQaFxZo1'
  environment: 'development'
  timeout: '20s'
cache:
  database: 0
  hostname: 'localhost'
  password: ''
  port: 6379
  testDatabase: 1
  expiration:
    page: '24h'
    staticFile: '4380h'
http:
  hostname: 'localhost'
  port: 8080
  tls:
    enabled: false
