name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 3

      - name: Install dependencies
        run: |
          go get ./...

      - name: Format code
        uses: iamnotaturtle/auto-gofmt@v1.0
        with:
          only_changed: True

      - name: Test
        run: go test -p 1 ./...
