name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 3

      - name: Install dependencies
        run: |
          go get ./...

      - name: Format code
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './src'
          gofmt-flags: '-l -d'

      - name: Test
        run: go test -p 1 ./...
