name: Code coverage
on: [push]

jobs:
  codecov:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: |
          go get ./...

      - name: Start containers
        run: |
          docker-compose up -d
          sleep 3

      - name: Run coverage
        run: |
          go test -race ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: true
