name: Code coverage
on: [push]

jobs:
  codecov:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18' # Use the Go version of your choice

      - name: Install dependencies
        run: go mod tidy

      - name: Generate code coverage
        run: |
          go test -v ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          file: ./coverage.txt
